# Generated by Django 3.1rc1 on 2020-08-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='postviews',
        ),
    ]
