# Generated by Django 3.1rc1 on 2020-08-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
