# Generated by Django 3.1rc1 on 2020-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200816_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/usr.png', upload_to='images'),
        ),
    ]
